### ISSUE TITLE
Does IF.glm() work for any family and link (especially non-canonical link)?

### ISSUE THREAD

**Issue by ge-li** [ohines/plmed#1]
```
IF.glm <- function(object,x=object$x){ 
  NROW(object$y)*(x*object$prior.weights*(object$y-object$fitted.values))%*%chol2inv(object$qr$qr)
}
```
The chol2inv(object$qr$qr) seems magic, can you elaborate, please? Thank you!

Under the canonical link, the estimating equation is x{y-mu(x^t b)}, hence the influence function (by the argument of Z-estimation) is [E{mu'(x^t b) x x^t}]^-1 {y-mu(x^t b)}x. My naive implementation is this:

```
glm_IF <- function(glm_obj) {
  # assume glm_obj fitted with x = True
  (glm_obj$x * glm_obj$prior.weights * (glm_obj$y - glm_obj$fitted.values)) %*%
    solve(crossprod(glm_obj$family$mu.eta(glm_obj$linear.predictors) * glm_obj$x, glm_obj$x) / NROW(glm_obj$y))
}
```
By the way, I just happened to google with "glm influence function" and your repo pops up. I'm also dealing with some two-step estimation which requires the first-step influence function. I thought it would be convenient to use the glm object.

**Comment by ge-li** [comment]
A little demo I did for sanity checks. Under the canonical link "logit" both your IF.glm() and mine glm_IF() works fine. However, when I change the data generating process to be "probit" and fit the data using the corresponding non-canonical link, the two functions disagree. I don't think my glm_IF() is accurate under a non-canonical link, but the estimated covariance matrix seems to match the vcov() results more closely than your IF.glm(). Do you have any thoughts on this? Thanks!

```
dgp <- function(n = 1e3, eta_0 = 1, eta_1 = 2, eta_2 = -3, ps_link = "logit") {
  # some random data generating process that simulate propensity scores ps
  # and treatment assignment z
  x_1 <- rnorm(n) # covariate 1
  x_2 <- rnorm(n) # covariate 2
  # propensity score
  ps <- make.link(ps_link)$linkinv(eta_0 + eta_1 * x_1 + eta_2 * x_2)
  z <- sapply(ps, function(x) {rbinom(1, 1, x)}) # treatment assignment
  data.frame(x_1, x_2, ps, z)
}

set.seed(123)
df <- dgp(ps_link = "logit")
ps_model <- glm(z ~ x_1 + x_2, family = binomial(link = "logit"), df, x = T)

vcov(ps_model)
crossprod(glm_IF(ps_model)) / 1e6
crossprod(IF.glm(ps_model)) / 1e6
```
![image](https://user-images.githubusercontent.com/43152858/149444195-e4fd14af-f9cf-496c-9772-1b56c58bbdbb.png)

```
set.seed(123)
df <- dgp(ps_link = "probit")
ps_model <- glm(z ~ x_1 + x_2, family = binomial(link = "probit"), df, x = T)

vcov(ps_model)
crossprod(glm_IF(ps_model)) / 1e6
crossprod(IF.glm(ps_model)) / 1e6
```
![image](https://user-images.githubusercontent.com/43152858/149444219-724b4905-09f2-4353-9963-e9c339ce0fc4.png)

**Comment by ohines** [comment]
Hi, 
Glad to see you are using the code.

So the chol2inv function is indeed a little bit of magic that I originally took from the glm source code - see e.g. line 667 of [this repo](https://github.com/SurajGupta/r-source/blob/master/src/library/stats/R/glm.R).

Looking at the [source code](https://rdrr.io/cran/vcov/src/R/vcov.R) it seems that the vcov function is essentially just a wrapper for chol2inv to calculate the covariance matrix.

I believe that we would not expect the mean squared IF to be equivalent to the vcov matrix. Instead we would expect it to be equivalent to sandwich::vcovHC. 

Below I have modified the IF.glm function to make better use of the sandwich package in R. Seems to solve the problem by extracting "working" residuals in the [estfun function](https://rdrr.io/cran/sandwich/src/R/estfun.R).

This code follows on from that in your comment:
```R
IF.glm2 <- function(object){ 
  sandwich::estfun(object)%*%sandwich::bread(object)
}

vcov(ps_model)
chol2inv(ps_model$qr$qr)
crossprod(IF.glm2(ps_model)) / 1e6
sandwich::vcovHC(ps_model,type="HC")
```

**Comment by ge-li** [comment]
Wow, I didn't know the sandwich package before. This is extremely helpful. Thank you so much!
